### ISSUE TITLE
ERROR: Error loading VS DTE. Is the correct version of Visual Studio and TwinCAT installed? Is the TcUnit-Runner running with administrator privileges?

### ISSUE THREAD

**Issue by Lokixin** [tcunit/TcUnit-Runner#19]
Hi, i am trying to use the TcUnit-Runner to automate unit tests with jenkins. During the job execution I am getting the following error:

C:\Users\jenkins\AppData\Local\Jenkins\.jenkins\workspace\LCS>"C:\Program Files (x86)\TcUnit-Runner\LaunchTcUnit.bat"
Task name of the TcUnit task not provided. Assuming only one task in TwinCAT solution
AmsNetId to run TwinCAT/TcUnit is not provided. Assuming TwinCAT/TcUnit will run locally '127.0.0.1.1.1'
A TwinCAT version is not provided. Assuming latest TwinCAT version should be used
Timeout not provided.
VISUAL_STUDIO_SOLUTION_PATH found!
The filepath to the visual studio solution file is: "path/to/file"
2021-02-23 10:50:23 - TcUnit-Runner build: 0.9.3.0
2021-02-23 10:50:23 - TcUnit-Runner build date: 22/12/2020
2021-02-23 10:50:23 - Visual Studio solution path: path/to/file
2021-02-23 10:50:23 - 
2021-02-23 10:50:23 - In TwinCAT project file, found TwinCAT version 3.1.4024.11
2021-02-23 10:50:23 - In Visual Studio solution file, found visual studio version 16.0
2021-02-23 10:50:23 - Version is pinned: False
2021-02-23 10:50:23 - Trying to load the Visual Studio Development Tools Environment (DTE) version 'TcXaeShell.DTE.16.0' ...
2021-02-23 10:50:23 - ...FAILED!
2021-02-23 10:50:23 - Trying to load the Visual Studio Development Tools Environment (DTE) version 'VisualStudio.DTE.16.0' ...
2021-02-23 10:50:26 - ...SUCCESSFUL!
2021-02-23 10:50:33 - ERROR: Error loading VS DTE. Is the correct version of Visual Studio and TwinCAT installed? Is the TcUnit-Runner running with administrator privileges?
2021-02-23 10:50:33 - Exiting application...
Exit code is 11 

I have followed the [user manual](https://tcunit.org/tcunit-runner-user-manual/#quick-start) steps and I have duble checked that both twinCAT and Visual Studio versions are correct, i have also added administrator privileges to the tcUnit-runner application via: properties -> compatibility -> run as administrator. But i keep getting the same output. 

However, if I run the tcunit-runner from the command line, i get the following output: 

2021-02-23 11:19:30 - TcUnit-Runner build: 0.9.3.0
2021-02-23 11:19:30 - TcUnit-Runner build date: 22/12/2020
2021-02-23 11:19:30 - Visual Studio solution path: C:\Projects\M2M3\M2\LCS\LCS_TestJenkins.sln
2021-02-23 11:19:30 -
2021-02-23 11:19:30 - In TwinCAT project file, found TwinCAT version 3.1.4024.11
2021-02-23 11:19:30 - In Visual Studio solution file, found visual studio version 16.0
2021-02-23 11:19:30 - Version is pinned: False
2021-02-23 11:19:30 - Trying to load the Visual Studio Development Tools Environment (DTE) version 'TcXaeShell.DTE.16.0' ...
2021-02-23 11:19:30 - ...FAILED!
2021-02-23 11:19:30 - Trying to load the Visual Studio Development Tools Environment (DTE) version 'VisualStudio.DTE.16.0' ...
2021-02-23 11:19:39 - ...SUCCESSFUL!
2021-02-23 11:20:04 - Using the TwinCAT remote manager to load TwinCAT version '3.1.4024.11'...
2021-02-23 11:20:38 - No task name provided. Assuming only one task exists
2021-02-23 11:20:38 - Found task with name 'PlcTask_Test'
2021-02-23 11:20:55 - Setting target NetId to '127.0.0.1.1.1'
2021-02-23 11:20:55 - Enabling boot project and setting BootProjectAutostart on 127.0.0.1.1.1
2021-02-23 11:21:23 - Waiting for results from TcUnit...
2021-02-23 11:21:34 - ... got 1 report lines so far.
2021-02-23 11:22:30 - ... got 105 report lines so far.
2021-02-23 11:22:40 - ... got 105 report lines so far.
2021-02-23 11:22:51 - ... got 105 report lines so far.
2021-02-23 11:23:02 - ... got 105 report lines so far.
2021-02-23 11:23:12 - ... got 105 report lines so far.
2021-02-23 11:23:22 - ... got 105 report lines so far.
2021-02-23 11:23:33 - ... got 105 report lines so far.
2021-02-23 11:23:43 - ... got 105 report lines so far.

Any idea on what am i doing wrong? Thanks for the help.

**Comment by sagatowski** [comment]
Hi!

What level is the Jenkins-service started with?
I've had a similar issue previously, and I have documented the issue here:
https://alltwincat.com/2018/10/04/ci-cd-with-twincat-part-four/

**Comment by Lokixin** [comment]
Hi, 

Thanks for your response. I have checked your link, so I wen to services->jenkins->properties->log in and I ensured that it is logged in with an admin account. I also restarted the service, but i am still getting the same error.

**Comment by sagatowski** [comment]
What user does The devenv process start as? Can you try to run tcunit runner Manually ad that user using pstools and see what the output is like? https://docs.microsoft.com/en-us/sysinternals/downloads/pstools

**Comment by BuStoLeuCa** [comment]
Hi, my problem might be unrelated but looks a bit similar to what Lokixin has. I am also trying to TcUnit-Runner for automating unit tests, but TcUnit-Runner does not seem to get the expected error messages. I've ran the batch file from cmd with administrator rights on both cmd and TcUnit-Runner and received the following results:

> C:\>"C:\Program Files (x86)\TcUnit-Runner\LaunchTcUnit.bat"
Task name of the TcUnit task not provided. Assuming only one task in TwinCAT solution
AmsNetId to run TwinCAT/TcUnit is not provided. Assuming TwinCAT/TcUnit will run locally '127.0.0.1.1.1'
A TwinCAT version is not provided. Assuming latest TwinCAT version should be used
Timeout not provided.
VISUAL_STUDIO_SOLUTION_PATH found!
The filepath to the visual studio solution file is: "C:\Users\bustoleuca\Documents\unit-test-example\unitTest.sln"
2021-02-24 10:58:36 - TcUnit-Runner build: 0.9.3.0
2021-02-24 10:58:36 - TcUnit-Runner build date: 22/12/2020
2021-02-24 10:58:36 - Visual Studio solution path: C:\Users\bustoleuca\Documents\unit-test-example\unitTest.sln
2021-02-24 10:58:36 -
2021-02-24 10:58:36 - In TwinCAT project file, found TwinCAT version 3.1.4024.11
2021-02-24 10:58:36 - In Visual Studio solution file, found visual studio version 15.0
2021-02-24 10:58:36 - Version is pinned: False
2021-02-24 10:58:36 - Trying to load the Visual Studio Development Tools Environment (DTE) version 'TcXaeShell.DTE.15.0' ...
2021-02-24 10:58:47 - ...SUCCESSFUL!
2021-02-24 10:59:10 - Using the TwinCAT remote manager to load TwinCAT version '3.1.4024.11'...
2021-02-24 10:59:35 - No task name provided. Assuming only one task exists
2021-02-24 10:59:35 - Found task with name 'PlcTask'
2021-02-24 10:59:54 - Setting target NetId to '127.0.0.1.1.1'
2021-02-24 10:59:54 - Enabling boot project and setting BootProjectAutostart on 127.0.0.1.1.1
2021-02-24 11:00:19 - Waiting for results from TcUnit...
2021-02-24 11:00:29 - ... got 0 report lines so far.
2021-02-24 11:00:39 - ... got 0 report lines so far.
2021-02-24 11:00:49 - ... got 0 report lines so far.
2021-02-24 11:00:59 - ... got 0 report lines so far.
2021-02-24 11:01:09 - ... got 0 report lines so far.
2021-02-24 11:01:19 - ... got 0 report lines so far.
2021-02-24 11:01:29 - ... got 0 report lines so far.
2021-02-24 11:01:39 - ... got 0 report lines so far.
2021-02-24 11:01:49 - ... got 0 report lines so far.
2021-02-24 11:01:59 - ... got 0 report lines so far.

If
* a TCXAE Shell is open when I run the TcUnit-Runner the report is received by TcUnit-Runner.
* I manually Start/Restart the Runtime from TwinCAT UI, TcUnit-Runner receives the report, but double the amount than expected.

Some additional info: I am running TwinCAT on a virtual machine. I've followed the guidelines about running on isolated cores. I have only trial license but I've renewed it recently, I don't know if that can be a problem.

Do I do something obviously wrong?

**Comment by sagatowski** [comment]
@BuStoLeuCa Will respond later, but regarding:

> "I manually Start/Restart the Runtime from TwinCAT UI, TcUnit-Runner receives the report, but double the amount than expected."

It might be related to this issue:
https://github.com/tcunit/TcUnit/issues/92
Can you verify?

**Comment by BuStoLeuCa** [comment]
Thanks for the quick response! I have only one TwinCAT project in my solution, so I don't think that issue applies.

**Comment by sagatowski** [comment]
@BuStoLeuCa But it might be other things than having dual TwinCAT projects (I think it's described in the issue). Can you run the project manually and see whether it also produces dual ADS-messages for the ordinary TwinCAT stuff? (not TcUnit)? The dual output has most likely nothing to do with TcUnit.

**Comment by sagatowski** [comment]
You actually don’t need to even run TcUnit to see this behaviour. Using your example, if you look into the error-list of Visual Studio you can see that you get a double of the other events as well:
image
![image](https://user-images.githubusercontent.com/33381702/108997230-9fee3c00-769f-11eb-9bc0-1b8ad4343e36.png)

**Comment by BuStoLeuCa** [comment]
I seem to get single output:
![Capture](https://user-images.githubusercontent.com/40433139/108997915-1be48600-7698-11eb-814d-7a17cf036a4e.PNG)

**Comment by sagatowski** [comment]
Interesting.
Is it possible for you to upload an example project where this can be re-produced?

**Comment by BuStoLeuCa** [comment]
I can, but I don't think it's the project, I've just reproduced the same issue with the [Advanced Example Project](https://github.com/tcunit/ExampleProjects/tree/master/AdvancedExampleProject). I might be missing something in setting up the environment.

**Comment by sagatowski** [comment]
@BuStoLeuCa That is very weird indeed. I just want to make sure I understand this correctly. You open the Advanced Example Project (manually), you run it (by manually activating the solution and running it), and in the Visual Studio Error list you get double the ADS-messages (but only from TcUnit)? Is that correct?

What version are you running of Visual Studio?
What version of TwinCAT are you running in the runtime that executes the code?

I would need to re-produce this error, I've never seen it.

**Comment by sagatowski** [comment]
@Lokixin  Did you have time to investigate what user the dev-env process is running as, and try to run it from the command using PsTools?

**Comment by Lokixin** [comment]
Hi, 
I need to give a bit of background: 
- Jenkins is installed in a Windows 10 Virtual Machine.

- The Jenkins service is running with a local admin user.

- If I log in to the virtual machine with a Domain Admin user, and I manually run the TCUnit-Runner with the Command Line it works fine. In this case the dev-env process is the domain admin and not the local admin. 

- I could not manage to use the PsTools because i always get access denied. 

Finally, when i run the TCUnit-Runner with Jenkins, the dev-env process user is the local admin and it produces the error reported previously.

**Comment by sagatowski** [comment]
It sounds like (for some reason) the domain admin has higher rights than the local admin, and that local admin can't provide the access right necessary to run TcUnit-Runner. You need to make sure that you can run TcUnit-Runner **manually** with the same user that executes it using Jenkins. A way of testing this is PsTools, which you can't run for some reason, and I guess this is because the local admin user doesn't have the access rights that you need.

**Comment by sagatowski** [comment]
@Lokixin I've only had this issue twice, and in both cases they've been resolved like I've written in my blog, that is making sure that it's possible to run TcUnit-Runner manually with a certain user, and then making sure that user is being used for the job execution in Jenkins.

**Comment by Lokixin** [comment]
Yes probably i need to grant the same privileges to the local admin. I'll try to grant these and run manually the tcunit-runner. Thanks a lot for all your attention, it was very helpful!

**Comment by sagatowski** [comment]
@Lokixin Great. Thank you for your feedback, it's invaluable! Make sure to let me know how it went. Once we know exactly what is wrong, I will most likely add something to the [F.A.Q. of the TcUnit-Runner](https://tcunit.org/frequently-asked-questions/), so that other people can re-use the knowledge that has been gained from this.

**Comment by BuStoLeuCa** [comment]
Sorry, I wasn't clear. What I am doing is:
* Run TcUnit-Runner manually through the batch file
* Wait until I see "... got 0 report lines so far." showing up on console for a few times
* From the Windows Task bar I select the TwinCAT UI->System->Start/Restart
* After that TcUnit-Runner is able to collect the error messages. On the other hand it seems to collect both the messages that were produced after the first TwinCAT Runtime restart initiated from the runner and the ones that were produced after the second restart initiated manually. 
I've added logging of the retreived error messages to the TcUnit-Runner and this is how it looks like:

> 2021-03-01 10:35:57 - TcUnit-Runner build: 0.9.3.0
2021-03-01 10:35:57 - TcUnit-Runner build date: 01/03/2021
2021-03-01 10:35:57 - Visual Studio solution path: C:\Users\smokey\Documents\TcXaeShell\AdvancedExampleProject-master\IOLink.sln
2021-03-01 10:35:57 - 
2021-03-01 10:35:57 - In TwinCAT project file, found TwinCAT version 3.1.4024.11
2021-03-01 10:35:57 - In Visual Studio solution file, found visual studio version 12.0
2021-03-01 10:35:57 - Version is pinned: False
2021-03-01 10:35:57 - Trying to load the Visual Studio Development Tools Environment (DTE) version 'VisualStudio.DTE.12.0' ...
2021-03-01 10:35:57 - ...FAILED!
2021-03-01 10:35:57 - Trying to load the Visual Studio Development Tools Environment (DTE) version 'VisualStudio.DTE.16.0' ...
2021-03-01 10:35:57 - ...FAILED!
2021-03-01 10:35:57 - Trying to load the Visual Studio Development Tools Environment (DTE) version 'TcXaeShell.DTE.15.0' ...
2021-03-01 10:36:01 - ...SUCCESSFUL!
2021-03-01 10:36:16 - Using the TwinCAT remote manager to load TwinCAT version '3.1.4024.11'...
2021-03-01 10:36:37 - Setting task 'PlcTask' enable and autostart, and all other tasks (if existing) to disable and non-autostart
2021-03-01 10:37:17 - Setting target NetId to '127.0.0.1.1.1'
2021-03-01 10:37:17 - Enabling boot project and setting BootProjectAutostart on 127.0.0.1.1.1
2021-03-01 10:37:46 - Waiting for results from TcUnit...
2021-03-01 10:37:56 - ... got 0 report lines so far.
2021-03-01 10:38:06 - ... got 0 report lines so far.
2021-03-01 10:38:16 - ... got 0 report lines so far.
2021-03-01 10:38:26 - ... got 0 report lines so far.
2021-03-01 10:38:36 - ... got 0 report lines so far.
2021-03-01 10:38:46 - ... got 0 report lines so far.
2021-03-01 10:38:56 - ... got 0 report lines so far.
2021-03-01 10:39:06 - ... got 0 report lines so far.
2021-03-01 10:39:16 - ... got 158 report lines so far.
2021-03-01 10:39:16 - All results from TcUnit obtained
2021-03-01 10:39:26 - Description: 01/03/2021 10:37:46 557 ms | 'TwinCAT System' (10000): TwinCAT System Restart initiated from AmsNetId: 192.168.123.9.1.1 port 33181.
2021-03-01 10:39:26 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:26 - Filename: 
2021-03-01 10:39:26 - Description: 01/03/2021 10:37:46 689 ms | 'TwinCAT System' (10000): Saving configuration of COM server TcEventLogger !
2021-03-01 10:39:26 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:26 - Filename: 
2021-03-01 10:39:26 - Description: 01/03/2021 10:37:47 488 ms | 'TwinCAT System' (10000): Shutting down COM Server TcEventLogger !
2021-03-01 10:39:26 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:26 - Filename: 
2021-03-01 10:39:26 - Description: 01/03/2021 10:37:49 397 ms | 'TwinCAT System' (10000): Loading configuration of COM server TcEventLogger !
2021-03-01 10:39:26 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:26 - Filename: 
2021-03-01 10:39:26 - Description: 01/03/2021 10:37:49 398 ms | 'TwinCAT System' (10000): Initializing COM Server TcEventLogger !
2021-03-01 10:39:26 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:26 - Filename: 
2021-03-01 10:39:26 - Description: 01/03/2021 10:37:49 406 ms | 'TwinCAT System' (10000): TcIo Server started: TcIo.
2021-03-01 10:39:26 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:26 - Filename: 
2021-03-01 10:39:26 - Description: 01/03/2021 10:37:49 413 ms | 'TwinCAT System' (10000): TcPlc30 Server started: TcPlc30.
2021-03-01 10:39:26 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:26 - Filename: 
2021-03-01 10:39:26 - Description: 01/03/2021 10:37:49 418 ms | 'TwinCAT System' (10000): TcRtsObjects Server started: TcRtsObjects.
2021-03-01 10:39:26 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:26 - Filename: 
2021-03-01 10:39:26 - Description: 01/03/2021 10:37:49 423 ms | 'TwinCAT System' (10000): TcRTime Server started: TcRTime.
2021-03-01 10:39:26 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:26 - Filename: 
2021-03-01 10:39:26 - Description: 01/03/2021 10:37:49 425 ms | 'TCRTIME' (200): System configured for 2 packages, 2 are activated for real-time
2021-03-01 10:39:26 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:26 - Filename: 
2021-03-01 10:39:26 - Description: 01/03/2021 10:37:49 531 ms | 'License Server' (30): license validation status is Valid(3)
2021-03-01 10:39:26 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:26 - Filename: 
2021-03-01 10:39:26 - Description: 01/03/2021 10:37:49 880 ms | 'PlcTask' (350): | Test suite ID=0 'PRG_TEST.fbDiagnosticMessageDiagnosticCodeParser_Test'
2021-03-01 10:39:26 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:26 - Filename: 
2021-03-01 10:39:26 - Description: 01/03/2021 10:37:49 883 ms | 'TwinCAT System' (10000): Starting COM Server TcEventLogger !
2021-03-01 10:39:26 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:26 - Filename: 
2021-03-01 10:39:26 - Description: 01/03/2021 10:37:49 900 ms | 'PlcTask' (350): | ID=0 number of tests=4, number of failed tests=0
2021-03-01 10:39:26 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:26 - Filename: 
2021-03-01 10:39:26 - Description: 01/03/2021 10:37:49 920 ms | 'PlcTask' (350): | Test name=WhenEmergencyErrorCodeExpectEmergencyErrorCode
2021-03-01 10:39:26 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:26 - Filename: 
2021-03-01 10:39:26 - Description: 01/03/2021 10:37:49 940 ms | 'PlcTask' (350): | Test class name=PRG_TEST.fbDiagnosticMessageDiagnosticCodeParser_Test
2021-03-01 10:39:26 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:26 - Filename: 
2021-03-01 10:39:26 - Description: 01/03/2021 10:37:49 960 ms | 'PlcTask' (350): | Test status=PASS, number of asserts=2
2021-03-01 10:39:26 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:26 - Filename: 
2021-03-01 10:39:26 - Description: 01/03/2021 10:37:49 980 ms | 'PlcTask' (350): | Test name=WhenManufacturerSpecificExpectManufacturerSpecific
2021-03-01 10:39:26 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:26 - Filename: 
2021-03-01 10:39:26 - Description: 01/03/2021 10:37:50 000 ms | 'PlcTask' (350): | Test class name=PRG_TEST.fbDiagnosticMessageDiagnosticCodeParser_Test
2021-03-01 10:39:26 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:26 - Filename: 
2021-03-01 10:39:26 - Description: 01/03/2021 10:37:50 020 ms | 'PlcTask' (350): | Test status=PASS, number of asserts=2
2021-03-01 10:39:26 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:26 - Filename: 
2021-03-01 10:39:26 - Description: 01/03/2021 10:37:50 040 ms | 'PlcTask' (350): | Test name=WhenProfileSpecificExpectProfileSpecific
2021-03-01 10:39:26 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:26 - Filename: 
2021-03-01 10:39:26 - Description: 01/03/2021 10:37:50 060 ms | 'PlcTask' (350): | Test class name=PRG_TEST.fbDiagnosticMessageDiagnosticCodeParser_Test
2021-03-01 10:39:26 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:26 - Filename: 
2021-03-01 10:39:26 - Description: 01/03/2021 10:37:50 080 ms | 'PlcTask' (350): | Test status=PASS, number of asserts=2
2021-03-01 10:39:26 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:26 - Filename: 
2021-03-01 10:39:26 - Description: 01/03/2021 10:37:50 100 ms | 'PlcTask' (350): | Test name=WhenReservedForFutureUseExpectReservedForFutureUse
2021-03-01 10:39:26 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:26 - Filename: 
2021-03-01 10:39:26 - Description: 01/03/2021 10:37:50 120 ms | 'PlcTask' (350): | Test class name=PRG_TEST.fbDiagnosticMessageDiagnosticCodeParser_Test
2021-03-01 10:39:26 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:26 - Filename: 
2021-03-01 10:39:26 - Description: 01/03/2021 10:37:50 140 ms | 'PlcTask' (350): | Test status=PASS, number of asserts=2
2021-03-01 10:39:26 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:26 - Filename: 
2021-03-01 10:39:26 - Description: 01/03/2021 10:37:50 160 ms | 'PlcTask' (350): | Test suite ID=1 'PRG_TEST.fbDiagnosticMessageFlagsParser_Test'
2021-03-01 10:39:26 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:26 - Filename: 
2021-03-01 10:39:26 - Description: 01/03/2021 10:37:50 180 ms | 'PlcTask' (350): | ID=1 number of tests=4, number of failed tests=0
2021-03-01 10:39:26 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:26 - Filename: 
2021-03-01 10:39:26 - Description: 01/03/2021 10:37:50 200 ms | 'PlcTask' (350): | Test name=WhenInfoMessageExpectInfoMessageGlobalTimestampAndZeroParameters
2021-03-01 10:39:26 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:26 - Filename: 
2021-03-01 10:39:26 - Description: 01/03/2021 10:37:50 220 ms | 'PlcTask' (350): | Test class name=PRG_TEST.fbDiagnosticMessageFlagsParser_Test
2021-03-01 10:39:26 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:26 - Filename: 
2021-03-01 10:39:26 - Description: 01/03/2021 10:37:50 240 ms | 'PlcTask' (350): | Test status=PASS, number of asserts=3
2021-03-01 10:39:26 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:26 - Filename: 
2021-03-01 10:39:26 - Description: 01/03/2021 10:37:50 260 ms | 'PlcTask' (350): | Test name=WhenWarningMessageExpectWarningMessageLocalTimestampAndTwoParameters
2021-03-01 10:39:26 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:50 280 ms | 'PlcTask' (350): | Test class name=PRG_TEST.fbDiagnosticMessageFlagsParser_Test
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:50 300 ms | 'PlcTask' (350): | Test status=PASS, number of asserts=3
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:50 320 ms | 'PlcTask' (350): | Test name=WhenErrorMessageExpectErrorMessageLocalTimestampAndFourParameters
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:50 340 ms | 'PlcTask' (350): | Test class name=PRG_TEST.fbDiagnosticMessageFlagsParser_Test
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:50 360 ms | 'PlcTask' (350): | Test status=PASS, number of asserts=3
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:50 380 ms | 'PlcTask' (350): | Test name=WhenReservedForFutureUseMessageExpectReservedForFutureUseMessageLocalTimestampAnd33Parameters
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:50 400 ms | 'PlcTask' (350): | Test class name=PRG_TEST.fbDiagnosticMessageFlagsParser_Test
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:50 420 ms | 'PlcTask' (350): | Test status=PASS, number of asserts=3
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:50 440 ms | 'PlcTask' (350): | Test suite ID=2 'PRG_TEST.fbDiagnosticMessageParser_Test'
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:50 460 ms | 'PlcTask' (350): | ID=2 number of tests=4, number of failed tests=0
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:50 480 ms | 'PlcTask' (350): | Test name=TestWithEmergencyMessage
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:50 500 ms | 'PlcTask' (350): | Test class name=PRG_TEST.fbDiagnosticMessageParser_Test
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:50 520 ms | 'PlcTask' (350): | Test status=PASS, number of asserts=7
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:50 540 ms | 'PlcTask' (350): | Test name=TestWithManufacturerSpecificMessage
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:50 560 ms | 'PlcTask' (350): | Test class name=PRG_TEST.fbDiagnosticMessageParser_Test
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:50 580 ms | 'PlcTask' (350): | Test status=PASS, number of asserts=7
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:50 600 ms | 'PlcTask' (350): | Test name=TestWithUnspecifiedMessageMessage
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:50 620 ms | 'PlcTask' (350): | Test class name=PRG_TEST.fbDiagnosticMessageParser_Test
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:50 640 ms | 'PlcTask' (350): | Test status=PASS, number of asserts=7
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:50 660 ms | 'PlcTask' (350): | Test name=TestWithUnspecifiedMessageMessage_ParameterVariant
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:50 680 ms | 'PlcTask' (350): | Test class name=PRG_TEST.fbDiagnosticMessageParser_Test
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:50 700 ms | 'PlcTask' (350): | Test status=PASS, number of asserts=7
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:50 720 ms | 'PlcTask' (350): | Test suite ID=3 'PRG_TEST.fbDiagnosticMessageTextIdentityParser_Test'
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:50 740 ms | 'PlcTask' (350): | ID=3 number of tests=3, number of failed tests=0
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:50 760 ms | 'PlcTask' (350): | Test name=WhenTextIdentityLowExpectTextIdentity0
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:50 780 ms | 'PlcTask' (350): | Test class name=PRG_TEST.fbDiagnosticMessageTextIdentityParser_Test
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:50 800 ms | 'PlcTask' (350): | Test status=PASS, number of asserts=1
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:50 820 ms | 'PlcTask' (350): | Test name=WhenTextIdentityHighExpectTextIdentity65535
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:50 840 ms | 'PlcTask' (350): | Test class name=PRG_TEST.fbDiagnosticMessageTextIdentityParser_Test
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:50 860 ms | 'PlcTask' (350): | Test status=PASS, number of asserts=1
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:50 880 ms | 'PlcTask' (350): | Test name=WhenTextIdentityMedExpectTextIdentity34500
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:50 900 ms | 'PlcTask' (350): | Test class name=PRG_TEST.fbDiagnosticMessageTextIdentityParser_Test
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:50 920 ms | 'PlcTask' (350): | Test status=PASS, number of asserts=1
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:50 940 ms | 'PlcTask' (350): | Test suite ID=4 'PRG_TEST.fbDiagnosticMessageTimeStampParser_Test'
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:50 960 ms | 'PlcTask' (350): | ID=4 number of tests=2, number of failed tests=0
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:50 980 ms | 'PlcTask' (350): | Test name=TestWithTimestampZeroTimeExpectCurrentTime
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:51 000 ms | 'PlcTask' (350): | Test class name=PRG_TEST.fbDiagnosticMessageTimeStampParser_Test
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:51 020 ms | 'PlcTask' (350): | Test status=PASS, number of asserts=1
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:51 040 ms | 'PlcTask' (350): | Test name=TestWithValidTimestampExpectSameTimestamp
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:51 060 ms | 'PlcTask' (350): | Test class name=PRG_TEST.fbDiagnosticMessageTimeStampParser_Test
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:51 080 ms | 'PlcTask' (350): | Test status=PASS, number of asserts=1
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:51 100 ms | 'PlcTask' (350): | ==========TESTS FINISHED RUNNING==========
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelHigh
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:51 120 ms | 'PlcTask' (350): | Test suites: 5
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelHigh
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:51 140 ms | 'PlcTask' (350): | Tests: 17
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelHigh
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:51 160 ms | 'PlcTask' (350): | Successful tests: 17
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelHigh
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:51 180 ms | 'PlcTask' (350): | Failed tests: 0
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelHigh
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:37:51 200 ms | 'PlcTask' (350): | ======================================
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelHigh
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:11 890 ms | 'TwinCAT System' (10000): TwinCAT System Service Control Message: SYSTEM START.
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:12 021 ms | 'TwinCAT System' (10000): Saving configuration of COM server TcEventLogger !
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:12 333 ms | 'TwinCAT System' (10000): Shutting down COM Server TcEventLogger !
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:14 184 ms | 'TwinCAT System' (10000): Loading configuration of COM server TcEventLogger !
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:14 185 ms | 'TwinCAT System' (10000): Initializing COM Server TcEventLogger !
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:14 192 ms | 'TwinCAT System' (10000): TcIo Server started: TcIo.
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:14 200 ms | 'TwinCAT System' (10000): TcPlc30 Server started: TcPlc30.
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:14 205 ms | 'TwinCAT System' (10000): TcRtsObjects Server started: TcRtsObjects.
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:14 210 ms | 'TwinCAT System' (10000): TcRTime Server started: TcRTime.
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:14 213 ms | 'TCRTIME' (200): System configured for 2 packages, 2 are activated for real-time
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:14 319 ms | 'License Server' (30): license validation status is Valid(3)
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:14 658 ms | 'PlcTask' (350): | Test suite ID=0 'PRG_TEST.fbDiagnosticMessageDiagnosticCodeParser_Test'
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:14 675 ms | 'TwinCAT System' (10000): Starting COM Server TcEventLogger !
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:14 678 ms | 'PlcTask' (350): | ID=0 number of tests=4, number of failed tests=0
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:14 698 ms | 'PlcTask' (350): | Test name=WhenEmergencyErrorCodeExpectEmergencyErrorCode
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:14 718 ms | 'PlcTask' (350): | Test class name=PRG_TEST.fbDiagnosticMessageDiagnosticCodeParser_Test
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:14 738 ms | 'PlcTask' (350): | Test status=PASS, number of asserts=2
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:14 758 ms | 'PlcTask' (350): | Test name=WhenManufacturerSpecificExpectManufacturerSpecific
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:14 778 ms | 'PlcTask' (350): | Test class name=PRG_TEST.fbDiagnosticMessageDiagnosticCodeParser_Test
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:14 798 ms | 'PlcTask' (350): | Test status=PASS, number of asserts=2
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:14 818 ms | 'PlcTask' (350): | Test name=WhenProfileSpecificExpectProfileSpecific
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:14 838 ms | 'PlcTask' (350): | Test class name=PRG_TEST.fbDiagnosticMessageDiagnosticCodeParser_Test
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:14 858 ms | 'PlcTask' (350): | Test status=PASS, number of asserts=2
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:14 878 ms | 'PlcTask' (350): | Test name=WhenReservedForFutureUseExpectReservedForFutureUse
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:14 898 ms | 'PlcTask' (350): | Test class name=PRG_TEST.fbDiagnosticMessageDiagnosticCodeParser_Test
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:14 918 ms | 'PlcTask' (350): | Test status=PASS, number of asserts=2
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:14 938 ms | 'PlcTask' (350): | Test suite ID=1 'PRG_TEST.fbDiagnosticMessageFlagsParser_Test'
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:14 958 ms | 'PlcTask' (350): | ID=1 number of tests=4, number of failed tests=0
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:14 978 ms | 'PlcTask' (350): | Test name=WhenInfoMessageExpectInfoMessageGlobalTimestampAndZeroParameters
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:14 998 ms | 'PlcTask' (350): | Test class name=PRG_TEST.fbDiagnosticMessageFlagsParser_Test
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 018 ms | 'PlcTask' (350): | Test status=PASS, number of asserts=3
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 038 ms | 'PlcTask' (350): | Test name=WhenWarningMessageExpectWarningMessageLocalTimestampAndTwoParameters
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 058 ms | 'PlcTask' (350): | Test class name=PRG_TEST.fbDiagnosticMessageFlagsParser_Test
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 078 ms | 'PlcTask' (350): | Test status=PASS, number of asserts=3
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 098 ms | 'PlcTask' (350): | Test name=WhenErrorMessageExpectErrorMessageLocalTimestampAndFourParameters
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 118 ms | 'PlcTask' (350): | Test class name=PRG_TEST.fbDiagnosticMessageFlagsParser_Test
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 138 ms | 'PlcTask' (350): | Test status=PASS, number of asserts=3
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 158 ms | 'PlcTask' (350): | Test name=WhenReservedForFutureUseMessageExpectReservedForFutureUseMessageLocalTimestampAnd33Parameters
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 178 ms | 'PlcTask' (350): | Test class name=PRG_TEST.fbDiagnosticMessageFlagsParser_Test
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 198 ms | 'PlcTask' (350): | Test status=PASS, number of asserts=3
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 218 ms | 'PlcTask' (350): | Test suite ID=2 'PRG_TEST.fbDiagnosticMessageParser_Test'
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 238 ms | 'PlcTask' (350): | ID=2 number of tests=4, number of failed tests=0
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 258 ms | 'PlcTask' (350): | Test name=TestWithEmergencyMessage
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 278 ms | 'PlcTask' (350): | Test class name=PRG_TEST.fbDiagnosticMessageParser_Test
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 298 ms | 'PlcTask' (350): | Test status=PASS, number of asserts=7
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 318 ms | 'PlcTask' (350): | Test name=TestWithManufacturerSpecificMessage
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 338 ms | 'PlcTask' (350): | Test class name=PRG_TEST.fbDiagnosticMessageParser_Test
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 358 ms | 'PlcTask' (350): | Test status=PASS, number of asserts=7
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 378 ms | 'PlcTask' (350): | Test name=TestWithUnspecifiedMessageMessage
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 398 ms | 'PlcTask' (350): | Test class name=PRG_TEST.fbDiagnosticMessageParser_Test
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 418 ms | 'PlcTask' (350): | Test status=PASS, number of asserts=7
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 438 ms | 'PlcTask' (350): | Test name=TestWithUnspecifiedMessageMessage_ParameterVariant
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 458 ms | 'PlcTask' (350): | Test class name=PRG_TEST.fbDiagnosticMessageParser_Test
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 478 ms | 'PlcTask' (350): | Test status=PASS, number of asserts=7
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 498 ms | 'PlcTask' (350): | Test suite ID=3 'PRG_TEST.fbDiagnosticMessageTextIdentityParser_Test'
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 518 ms | 'PlcTask' (350): | ID=3 number of tests=3, number of failed tests=0
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 538 ms | 'PlcTask' (350): | Test name=WhenTextIdentityLowExpectTextIdentity0
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 558 ms | 'PlcTask' (350): | Test class name=PRG_TEST.fbDiagnosticMessageTextIdentityParser_Test
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 578 ms | 'PlcTask' (350): | Test status=PASS, number of asserts=1
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 598 ms | 'PlcTask' (350): | Test name=WhenTextIdentityHighExpectTextIdentity65535
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 618 ms | 'PlcTask' (350): | Test class name=PRG_TEST.fbDiagnosticMessageTextIdentityParser_Test
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 638 ms | 'PlcTask' (350): | Test status=PASS, number of asserts=1
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 658 ms | 'PlcTask' (350): | Test name=WhenTextIdentityMedExpectTextIdentity34500
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 678 ms | 'PlcTask' (350): | Test class name=PRG_TEST.fbDiagnosticMessageTextIdentityParser_Test
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 698 ms | 'PlcTask' (350): | Test status=PASS, number of asserts=1
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 718 ms | 'PlcTask' (350): | Test suite ID=4 'PRG_TEST.fbDiagnosticMessageTimeStampParser_Test'
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 738 ms | 'PlcTask' (350): | ID=4 number of tests=2, number of failed tests=0
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 758 ms | 'PlcTask' (350): | Test name=TestWithTimestampZeroTimeExpectCurrentTime
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 778 ms | 'PlcTask' (350): | Test class name=PRG_TEST.fbDiagnosticMessageTimeStampParser_Test
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 798 ms | 'PlcTask' (350): | Test status=PASS, number of asserts=1
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 818 ms | 'PlcTask' (350): | Test name=TestWithValidTimestampExpectSameTimestamp
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 838 ms | 'PlcTask' (350): | Test class name=PRG_TEST.fbDiagnosticMessageTimeStampParser_Test
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 858 ms | 'PlcTask' (350): | Test status=PASS, number of asserts=1
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelLow
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 878 ms | 'PlcTask' (350): | ==========TESTS FINISHED RUNNING==========
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelHigh
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 898 ms | 'PlcTask' (350): | Test suites: 5
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelHigh
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 918 ms | 'PlcTask' (350): | Tests: 17
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelHigh
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 938 ms | 'PlcTask' (350): | Successful tests: 17
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelHigh
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 958 ms | 'PlcTask' (350): | Failed tests: 0
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelHigh
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - Description: 01/03/2021 10:39:15 978 ms | 'PlcTask' (350): | ======================================
2021-03-01 10:39:27 - ErrorLevel: vsBuildErrorLevelHigh
2021-03-01 10:39:27 - Filename: 
2021-03-01 10:39:27 - ERROR: While parsing TcUnit results, expected TEST_SUITE_FINISHED_RUNNING but got TEST_NAME
2021-03-01 10:39:27 - Closing the Visual Studio Development Tools Environment (DTE)...
2021-03-01 10:39:47 - Exiting application...

So the duplication of log messages is expected since the runtime is restarted twice so the tests are running twice. What I don't know, why the runner cannot retreive the error messages right after the first start/restart is issued by the TcUnit-Runner itself, and why doing a second manual restart makes it possible to collect those messages?

**Comment by sagatowski** [comment]
@BuStoLeuCa And if we forget the TcUnit-Runner all together, if you run the exact same project with the exact same version of TwinCAT and exact same version of Visual Studio, it ALWAYS works? I just want to make sure there is nothing weird with your running environment.

**Comment by BuStoLeuCa** [comment]
I've tried the following:
* Open TcXaeShell
* Open the IOLink Solution
* Hit the Restart TwinCAT System button (run mode)

Result: I did not see the errors showing up in the Error List window, however I see them in the Output window. Subsequent click on the restart button will lead to error messages appearing in the Error List window. If the TcUnit-Runner collects the messages from the Error List window that might be an explanation why it's not receiving the error messages.

**Comment by Traavaas** [comment]
I also end up with the same error when specifying my project to build in Visual Studio 2019 through the solution file. 
![image](https://user-images.githubusercontent.com/43027812/112192594-558bac80-8bc4-11eb-9067-e1b3448e3486.png)

When I try Visual Studio 2013 and 2017, it works perfectly fine.

**Comment by sagatowski** [comment]
> I've tried the following:
> 
> * Open TcXaeShell, TwinCAT is in config mode
> * Open the IOLink Solution
> * Hit the Restart TwinCAT System button (run mode)
> 
> Result: I did not see the errors showing up in the Error List window, however I see them in the Output window. Subsequent click on the restart button will lead to error messages appearing in the Error List window. If the TcUnit-Runner collects the messages from the Error List window that might be an explanation why it's not receiving the error messages.
> ![No error output](https://user-images.githubusercontent.com/40433139/112131800-d4cbb100-8bc1-11eb-92b7-149cd1b9d44b.PNG)

That's correct, that's the reason TcUnit-Runner can't collect the results then. TcUnit-Runner collects them from the error list. Why there are no messages showing up in your error list I cannot answer though, I've never seen this problem but obviously it's not a problem with TcUnit as you don't seem to get ANY messages from TwinCAT there. Maybe someone else has an idea?

**Comment by sagatowski** [comment]
> I also end up with the same error when specifying my project to build in Visual Studio 2019 through the solution file.
> ![image](https://user-images.githubusercontent.com/43027812/112192594-558bac80-8bc4-11eb-9067-e1b3448e3486.png)
> 
> When I try Visual Studio 2013 and 2017, it works perfectly fine. Any breakthroughs regarding this issue?

What happens if you load the project manually in Visual Studio 2019, and run the test manually? do you get the results in the error list then?

Also, could you upload your *.sln-file? I was not aware there was a 16.9, I just assumed there was always a zero (16.0, 15.0 etc).
But looking at this:
https://en.wikipedia.org/wiki/Microsoft_Visual_Studio

It seems that 16.9 is valid, and maybe what is written to the sln-file?

**Comment by Traavaas** [comment]
@sagatowski Thanks for the help! It's working now! I have no clue as to why it didn't work but this is what I did to fix it:

1. Uninstall and Reinstall Visual Studio 2019
2. Modify TwinCAT3 using the installer to integrate with Visual Studio 2019. 

I definitely tried this before to see if it would fix the bug but it did not seem to work until now for some odd reason.

**Comment by sagatowski** [comment]
@Traavaas That's great it worked. I have no idea what the problem was, but happy a complete re-install fixed it. If you like this project, please star it so others can find it! :-)

**Comment by BuStoLeuCa** [comment]
The AMS router info looks like this after running the tests:

![AMS Router Information](https://user-images.githubusercontent.com/40433139/112467318-d2eb2480-8d5e-11eb-9336-6e12e2a03aea.PNG)

**Comment by sagatowski** [comment]
@BuStoLeuCa This looks fine. I think this is a case for Beckhoff support, because you don't just get no messages from TcUnit, you don't get ANY messages from TwinCAT whatsoever! It's just completely empty... so it seems the problem is somewhere else!

**Comment by sagatowski** [comment]
@BuStoLeuCa If you still got a problem and Beckhoff haven't been able to help you, please create a separate issue in the TcUnit project as it seems this has nothing to do with the TcUnit-Runner.

**Comment by sagatowski** [comment]
@Lokixin Did you manage to solve the problem with user rights? What did you do in that case? I think I would need to add something to the F.A.Q., and would need your feedback.

**Comment by sagatowski** [comment]
@Lokixin If I don't receive any new updates in the two coming weeks I will assume the issue is resolved. If it's not, please re-open it and provide details.

**Comment by sagatowski** [comment]
@BuStoLeuCa Did you manage to figure out what the problem was?

**Comment by Rickymes** [comment]
I jakob,
I have the same issue described above, and I have also read your blog, but the problem still remain. Instead of Git as a version control system, I used SubVersion if it can help you to understand. Probably the versions of Visual Studio and TwinCAT installed are not ok?

![image](https://user-images.githubusercontent.com/96171639/146151228-2744d76c-b6b8-4325-9233-a2d6cc0b9aa3.png)

Thanks for the help.

**Comment by sagatowski** [comment]
> I jakob, I have the same issue described above, and I have also read your blog, but the problem still remain. Instead of Git as a version control system, I used SubVersion if it can help you to understand. Using the Shell it will work fine, reporting the results in a XML file. Probably the versions of Visual Studio and TwinCAT installed are not ok?
> 
> ![image](https://user-images.githubusercontent.com/96171639/146151228-2744d76c-b6b8-4325-9233-a2d6cc0b9aa3.png)
> 
> Thanks for the help.

Did you try the suggestions mentioned above?
What was your environment?

**Comment by Rickymes** [comment]
Yes, I have followed the suggestions mentioned and I'm in this situation:
- Jenkins is running on a Windows 11 PC
- The Jenkins service is running with a local system account
- TcUnit-Runner is running with administrator privileges

What do you mean with the dev-env process? How can I see that?

Thanks for your help.




Il giorno mer 15 dic 2021 alle ore 12:58 Jakob Sagatowski <
***@***.***> ha scritto:

**Comment by Rickymes** [comment]
If I run the TcUnit-Runner from the command prompt it works fine. I followed the suggestions written in the manual but also with the local admin account gave me the same error.

**Comment by sagatowski** [comment]
If it worked with command prompt then the problem is your Jenkins doesnt have the right access. You need to make sure Jenkins has the exact same access rights as your local admin rights (just as when you were running CMD).

**Comment by Bulkje** [comment]
I had this problem, was running as administrator and everything. The problem didn't occur when I had visual studio(2017) launched, only when calling from Azure Devops. I fixed it by installing VISX package "Microsoft Visual Studio Installer Projects".
It looks like an open box in the VS Marketplace. 

Can someone confirm this solving the issue?

**Comment by Bulkje** [comment]
I had this issue again, it seems to be linked to launching the application with a local account vs domain account? 
I found this Stackoverflow question that is very similar. https://stackoverflow.com/questions/7289620/activator-createinstanceguid-works-inside-vside-but-not-externally 
So the fix seems to be launching TcUnit-Runner with a local administrator account, and not with a domain account.
Ideally the DTE would be launched with local administrator / system privileges, but I can't find how to do that.
